config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users do
    resources :vocabs
  end

  root 'sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :vocabs
  has_secure_password
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :password, length: { minimum: 8 }, allow_nil: true

  before_create :create_remember_token

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/models/vocab.rb
class Vocab < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, :only => [:show,:edit]

  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

    puts "DERP#{current_user()}"
    if signed_in?
      redirect_to current_user
    end
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @current_user = current_user()
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    puts user_params[:password]
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def signed_in_user
      redirect_to session_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(users_url) unless current_user?(@user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/vocabs_controller.rb
class VocabsController < ApplicationController
  before_action :set_user
  before_action :check_auth , only: [:new, :create, :edit, :update, :destroy]
  before_action :set_vocab, only: [:show, :edit, :update, :destroy]

  # GET /vocabs
  # GET /vocabs.json
  def index
    @vocabs = Vocab.all().where(user_id: @user.id)
    @is_users = current_user?(@user)
  end

  # GET /vocabs/1
  # GET /vocabs/1.json
  def show
  end

  # GET /vocabs/new
  def new
    @vocab = Vocab.new
  end

  # GET /vocabs/1/edit
  def edit
  end

  # POST /vocabs
  # POST /vocabs.json
  def create
    @vocab = Vocab.new({user_id: @user.id}.merge(vocab_params))

    respond_to do |format|
      if @vocab.save
        format.html { redirect_to action: 'index', notice: 'Vocab was successfully created.' }
        format.json { render :show, status: :created, location: @vocab }
      else
        format.html { render :new }
        format.json { render json: @vocab.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vocabs/1
  # PATCH/PUT /vocabs/1.json
  def update
    respond_to do |format|
      if @vocab.update(vocab_params)
        format.html { redirect_to action: 'index', notice: 'Vocab was successfully updated.' }
        format.json { render :show, status: :ok, location: @vocab }
      else
        format.html { render :edit }
        format.json { render json: @vocab.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vocabs/1
  # DELETE /vocabs/1.json
  def destroy
    @vocab.destroy
    respond_to do |format|
      format.html { redirect_to vocabs_url, notice: 'Vocab was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_vocab
      @vocab = Vocab.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def check_auth
      unless current_user?(@user)
        redirect_to user_vocabs_path(@user)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vocab_params
      params.require(:vocab).permit(:user_id, :reference_lang, :learning_lang)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def authenticate_user!
    redirect_to(:controller => 'session', :action => 'new') unless current_user
  end


  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vocabs_helper.rb
module VocabsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VocabList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>E mail</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <%if user == @current_user%>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>E mail:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>
<%= link_to 'Vocabulary', user_vocabs_path(@user) %>

app/views/vocabs/_form.html.erb
<%= form_for([@user, @vocab]) do |f| %>
  <% if @vocab.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vocab.errors.count, "error") %> prohibited this vocab from being saved:</h2>

      <ul>
      <% @vocab.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :reference_lang %><br>
    <%= f.text_field :reference_lang %>
  </div>
  <div class="field">
    <%= f.label :learning_lang %><br>
    <%= f.text_field :learning_lang %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vocabs/edit.html.erb
<h1>Editing vocab</h1>

<%= render 'form' %>

<%= link_to 'Back', user_vocabs_path(@user) %>

app/views/vocabs/index.html.erb
<h1>Listing vocabs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Reference lang</th>
      <th>Learning lang</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vocabs.each do |vocab| %>
      <tr>
        <td><%= vocab.user_id %></td>
        <td><%= vocab.reference_lang %></td>
        <td><%= vocab.learning_lang %></td>
        <% if @is_users %>
          <td><%= link_to 'Edit', edit_user_vocab_path(@user, vocab) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @is_users %>
  <%= link_to 'New Vocab', new_user_vocab_path(@user.id) %>
<%end%>

app/views/vocabs/new.html.erb
<h1>New vocab</h1>

<%= render 'form' %>

<%= link_to 'Back', user_vocabs_path(@user) %>